spring: 
    profiles: 
        active:
           - dev
---
spring:
    profiles: dev
    application:
        name: spring-boot-14-springcloud-config-dev
---
spring:
    profiles: test
    application:
        name: spring-boot-14-springcloud-config-test