spring: 
    profiles: 
        active:
           - dev
---
server:
  port: 8761
spring:
    profiles: dev
    application:
        name: eureka-server1
eureka:
  instance:
    hostname: eureka-server1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
server:
  port: 8762
spring:
    profiles: test
    application:
        name: eureka-server2
eureka:
  instance:
    hostname: eureka-server2
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8762/eureka/